llama_recipe = {
    # 'model.layers.0.mlp':{'pr':0.2}, 
    # 'model.layers.0.self_attn':{'pr':0.2},
    # 'model.layers.1.mlp':{'pr':0.2}, 
    # 'model.layers.1.self_attn':{'pr':0.2},
    # 'model.layers.2.mlp':{'pr':0.2}, 
    # 'model.layers.2.self_attn':{'pr':0.2},
    # 'model.layers.3.mlp':{'pr':0.2}, 
    # 'model.layers.3.self_attn':{'pr':0.2},
    # 'model.layers.4.mlp':{'pr':0.2}, 
    # 'model.layers.4.self_attn':{'pr':0.2},
    'model.layers.5.mlp':{'pr':0.5}, 
    # 'model.layers.5.self_attn':{'pr':0.2},
    'model.layers.6.mlp':{'pr':0.5}, 
    # 'model.layers.6.self_attn':{'pr':0.2},
    'model.layers.7.mlp':{'pr':0.5}, 
    # 'model.layers.7.self_attn':{'pr':0.2},
    'model.layers.8.mlp':{'pr':0.5}, 
    # 'model.layers.8.self_attn':{'pr':0.1},
    'model.layers.9.mlp':{'pr':0.5}, 
    # 'model.layers.9.self_attn':{'pr':0.1},
    'model.layers.10.mlp':{'pr':0.5}, 
    # 'model.layers.10.self_attn':{'pr':0.2},
    # 'model.layers.11.mlp':{'pr':0.2}, 
    # 'model.layers.11.self_attn':{'pr':0.2},
    # 'model.layers.12.mlp':{'pr':0.2}, 
    # 'model.layers.12.self_attn':{'pr':0.2},
    'model.layers.13.mlp':{'pr':0.4}, 
    # 'model.layers.13.self_attn':{'pr':0.1},
    'model.layers.14.mlp':{'pr':0.4}, 
    # 'model.layers.14.self_attn':{'pr':0.1},
    'model.layers.15.mlp':{'pr':0.4}, 
    # 'model.layers.15.self_attn':{'pr':0.2},
    'model.layers.16.mlp':{'pr':0.4}, 
    # 'model.layers.16.self_attn':{'pr':0.2},
    'model.layers.17.mlp':{'pr':0.4}, 
    # 'model.layers.17.self_attn':{'pr':0.2},
    'model.layers.18.mlp':{'pr':0.4}, 
    # 'model.layers.18.self_attn':{'pr':0.2},
    'model.layers.19.mlp':{'pr':0.4}, 
    # 'model.layers.19.self_attn':{'pr':0.2},                                                                                                                                                                                                                                              
    'model.layers.20.mlp':{'pr':0.4}, 
    # 'model.layers.20.self_attn':{'pr':0.2},
    'model.layers.21.mlp':{'pr':0.4}, 
    # 'model.layers.21.self_attn':{'pr':0.2},
    'model.layers.22.mlp':{'pr':0.4}, 
    # 'model.layers.22.self_attn':{'pr':0.2},
    'model.layers.23.mlp':{'pr':0.4}, 
    # 'model.layers.23.self_attn':{'pr':0.2},
    'model.layers.24.mlp':{'pr':0.4}, 
    # 'model.layers.24.self_attn':{'pr':0.2},
    'model.layers.25.mlp':{'pr':0.4}, 
    # 'model.layers.25.self_attn':{'pr':0.1},
    'model.layers.26.mlp':{'pr':0.4}, 
    # 'model.layers.26.self_attn':{'pr':0.1},
    'model.layers.27.mlp':{'pr':0.4}, 
    # 'model.layers.27.self_attn':{'pr':0.1},
    # 'model.layers.28.mlp':{'pr':0.2}, 
    # 'model.layers.28.self_attn':{'pr':0.1},
    # 'model.layers.29.mlp':{'pr':0.2}, 
    # 'model.layers.29.self_attn':{'pr':0.1},
    # 'model.layers.30.mlp':{'pr':0.8}, 'model.layers.30.self_attn':{'pr':0.2},
    # 'model.layers.31.mlp':{'pr':0.2}, 'model.layers.31.self_attn':{'pr':0.2}
}
